draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_font(global.bigfont)
draw_set_colour(c_white)
draw_text_transformed(640, y - 360, "Die Hölle \nist kein \nZuhause", 2, 2, 0)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
draw_self()
draw_sprite(spr_credits, 0, x, y + 720)
draw_sprite(spr_credits, 1, x, y + 720 + 720)
draw_sprite(spr_credits,2, x, y + 720 + 720 + 720)
draw_set_colour(c_black)
draw_set_alpha(drawalpha)
draw_rectangle(0, 0, 1280, 720, false)
draw_set_alpha(1)
draw_set_colour(c_white)