draw_sprite(sprite_index, 0, x, y)
draw_sprite_ext(sprite_index, 3, x, y, 1, 1, 0, c_white, leftdooralpha)
draw_sprite_ext(sprite_index, 3, x+1950, y, -1, 1, 0, c_white, rightdooralpha)
draw_self()
draw_sprite(sprite_index, 2, x, y)
draw_sprite_ext(sprite_index, 3, x+1950, y, -1, 1, 0, c_white, 0)